site_name: POD_Deep-Learning
#from https://github.com/squidfunk/mkdocs-material
theme_dir: "material"

theme: 
  name: null
   
docs_dir: "docs"
repo_url: https://github.com/PrivateOrganizationDeepLearning/DeepLearning
site_url: http://poddeeplearning.readthedocs.io

markdown_extensions:
  - mdx_math
  - fenced_code
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  

extra_javascript: 
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

#pages:
#    - 'Home': 'index.md'
#    - Keras_Cookbook: 
#      - 2.simple_ann.md: Keras_Cookbook/2.simple_ann.md

